#!/usr/bin/env python3

MANIK_POCET_TYPOV  = 9
PRIKAZ_POCET_TYPOV = 6

MANIK_BANIK    = 0
MANIK_SEKAC    = 1
MANIK_MLATIC   = 2
MANIK_STRAZNIK = 3
MANIK_SKAUT    = 4
MANIK_STRELEC  = 5
MANIK_LOVEC    = 6
MANIK_KUCHAR   = 7
MANIK_KOVAC    = 8

MAPA_NEVIEM   = 0
MAPA_OKRAJ    = 1
MAPA_ZELEZO   = 2
MAPA_ZLATO    = 3
MAPA_SUTER    = 4
MAPA_VOLNO    = 5
MAPA_PASCA    = 6
MAPA_START    = 7

PRIKAZ_CHOD       = 1
PRIKAZ_UTOC       = 2
PRIKAZ_KUJ        = 3
PRIKAZ_DAJ_ZLATO  = 4
PRIKAZ_DAJ_ZELEZO = 5
PRIKAZ_DAJ_SPENAT = 6
