#!/usr/bin/env python3

import os
import sys
import random
from functools import partial
from time import time

from consts import *
from wrapper import (
    Teren, Stav, Prikaz, Mapa, Bod
)

# Use for debug prints
debug = partial(print, file=sys.stderr)

def init():
    # Vas kod tu
    pass


def next_moves(teren, stav):
    prikazy = []
    debug(stav.manici)
    for manik in stav.manici:
        if manik.ktoreho_hraca == 0:
            if manik.typ == MANIK_KOVAC:
                prikazy.append(Prikaz(manik.id, PRIKAZ_KUJ, Bod(manik.x, manik.y+1), MANIK_BANIK))
            elif manik.typ == MANIK_BANIK:
                prikazy.append(Prikaz(manik.id, PRIKAZ_CHOD, Bod(manik.x+1, manik.y)))

    return prikazy


def main():
    pid = os.getpid()
    epoch = int(time())
    random.seed(pid * epoch)
    print('START pid={}, seed={}'.format(pid, epoch), file=sys.stderr)

    mapa = Mapa.from_stdin()
    init()

    while True:
        teren = Teren.from_compressed()
        stav = Stav.form_stdin()

        prikazy = next_moves(teren, stav)
        print(len(prikazy))
        for prikaz in prikazy:
            print(prikaz)

        print('.', flush=True)

if __name__ == '__main__':
    main()
